app:
  name: "Magicbot"
  version: "0.1.0"
  debug: true

database:
  url: "${DATABASE_URL}"
  pool_size: 10
  max_overflow: 20

redis:
  url: "${REDIS_URL}"
  decode_responses: true

exchange:
  binance:
    testnet: true
    api_key: "${BINANCE_API_KEY}"
    secret_key: "${BINANCE_SECRET_KEY}"
    # Separate setting for backtesting data source
    backtesting_use_mainnet: true

risk_management:
  max_position_size: 0.1
  max_daily_loss: 0.05
  stop_loss_percentage: 0.02

strategies:
  enabled:
    - ma_crossover_simple
    - rsi_strategy
    - bollinger_bands
    - breakout_strategy
    - macd_strategy
    - momentum_strategy
    - stochastic_strategy
    - mean_reversion_rsi
    - ema_scalping_strategy
  
  ma_crossover_simple:
    symbols: ["BTCUSDT"]
    position_size: 0.02    # Larger position for fewer trades
    fast_period: 8         # Balanced periods for trend capture
    slow_period: 21        # Classic EMA periods
    timeframes: ["5m"]     # Use 5m to reduce noise  
    stop_loss_pct: 2.5     # Wider stops for crypto volatility
    take_profit_pct: 5.0   # Larger targets for trend following
    atr_period: 14         # Standard ATR period
    # Trailing stop loss configuration
    trailing_stop_enabled: true
    trailing_stop_distance: 1.8    # Wider trailing stop
    trailing_stop_type: "percentage"
  
  ma_crossover:
    symbols: ["BTCUSDT", "ETHUSDT"]
    position_size: 0.01
    # Enhanced MA periods to reduce whipsaws
    fast_period: 20        # Increased from 10
    slow_period: 50        # Increased from 30
    timeframes: ["1h"]
    # Risk management (now dynamic based on ATR)
    stop_loss_pct: 2.0
    take_profit_pct: 4.0
    # Volume confirmation
    volume_confirmation: true
    volume_period: 20
    volume_multiplier: 1.5
    # Momentum confirmation
    momentum_confirmation: true
    momentum_period: 14
    min_momentum_threshold: 0.5
    # Volatility-based position sizing
    atr_period: 14
    volatility_multiplier: 2.0
    # Enhanced filtering
    trend_strength_threshold: 0.001
    ma_separation_threshold: 0.002
    # Dynamic exits
    trailing_stop_multiplier: 2.0
    profit_target_multiplier: 3.0
  
  rsi_strategy:
    symbols: ["BTCUSDT", "ETHUSDT"]
    position_size: 0.01
    rsi_period: 14
    rsi_oversold: 30
    rsi_overbought: 70
    timeframes: ["1h"]
    # Risk management
    stop_loss_pct: 2.0
    take_profit_pct: 4.0
  
  bollinger_bands:
    symbols: ["BTCUSDT", "ETHUSDT"]
    position_size: 0.01
    period: 20
    std_dev: 2.0
    mean_reversion_threshold: 0.02
    timeframes: ["1h"]
    # Risk management
    stop_loss_pct: 2.0
    take_profit_pct: 4.0
  
  breakout_strategy:
    symbols: ["BTCUSDT", "ETHUSDT"]
    position_size: 0.01
    lookback_period: 20
    breakout_threshold: 1.02
    volume_confirmation: true
    min_volatility: 0.005
    timeframes: ["1h"]
    # Risk management
    stop_loss_pct: 2.5
    take_profit_pct: 5.0
  
  macd_strategy:
    symbols: ["BTCUSDT", "ETHUSDT"]
    position_size: 0.01
    macd_fast: 12
    macd_slow: 26
    macd_signal: 9
    histogram_threshold: 0.0
    timeframes: ["1h"]
    # Risk management
    stop_loss_pct: 2.0
    take_profit_pct: 4.0
  
  momentum_strategy:
    symbols: ["BTCUSDT", "ETHUSDT"]
    momentum_period: 14
    sma_period: 20
    momentum_threshold: 5.0
    volume_confirmation: true
    position_size: 0.01
  
  stochastic_strategy:
    symbols: ["BTCUSDT", "ETHUSDT"]
    k_period: 14
    d_period: 3
    smooth_period: 3
    oversold: 20
    overbought: 80
    divergence_lookback: 5
    position_size: 0.01
  
  mean_reversion_rsi:
    symbols: ["BTCUSDT", "ETHUSDT"]
    rsi_period: 14
    ma_period: 50
    extreme_oversold: 15
    oversold: 30
    overbought: 70
    extreme_overbought: 85
    rsi_ma_period: 5
    volume_confirmation: true
    position_size: 0.01
  
  ema_scalping_strategy:
    symbols: ["BTCUSDT", "ETHUSDT"]
    fast_ema: 5
    slow_ema: 13
    signal_ema: 21
    volume_period: 10
    volume_multiplier: 1.5
    rsi_period: 14
    rsi_overbought: 75
    rsi_oversold: 25
    stop_loss_pct: 0.5
    take_profit_pct: 1.0
    risk_reward_ratio: 2.0
    min_price_movement: 0.1
    consolidation_period: 3
    position_size: 0.02
  
