# Production Configuration
database:
  url: "postgresql://user:password@localhost:5432/magicbot"
  echo: false

api:
  host: "0.0.0.0"
  port: 8000
  debug: false

exchange:
  binance:
    testnet: false
    api_key: "${BINANCE_API_KEY}"
    secret_key: "${BINANCE_SECRET_KEY}"
    # Separate setting for backtesting data source
    backtesting_use_mainnet: true

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

risk:
  max_position_size: 0.02
  max_daily_loss: 0.01
